### ISSUE TITLE
Clipboard not clipboarding

### ISSUE THREAD

**Issue by rushtothesun** [lemasato/POE-Trades-Companion#87] opened 2017-12-12 23:27 UTC
This seems to happen more often on Gems. Even clicking the clipboard item button doesn't copy it.

**Comment by sclient** [comment] 2017-12-16 21:05
I am having the same issue. I get the whisper but it wont copy the item to search for in the search box like it used to. I am reverting to stable.

**Comment by lemasato** [comment] 2017-12-23 18:14
Are you using a clipboard manager or any kind of program that could interfer with the clipboard? It could be related to that.

**Comment by rushtothesun** [comment] 2017-12-24 04:39
Not that I know of. It happens at random, but it seems to happen more often with gems. Also pressing the thank you button sometimes posts the item in local chat instead of saying thanks and kicking the person from the party. Maybe they're related?

**Comment by lemasato** [comment] 2017-12-24 05:02
Yeah I've seen that one happening myself.  
Pressing the "Invite" button would send the item's name in local chat (instead of the 1st custom message) but it would still invite the buyer afterwards. Same would happen with my "Thanks" button (which also has 2 custom messages set).

Someone reported the same issue on the [forums](https://www.pathofexile.com/forum/view-thread/1755148/page/32#p15122248). I thought it could be some conflicts related to TradeMacro since everything was working previously without any changes on my end.  
Either way, I can probably work something out on my end (at least, avoid sending wrong messages and tell the user if the script is unable to clipboard something)

**Comment by rushtothesun** [comment] 2017-12-28 03:17
I'll let you know if I encounter it again

**Comment by rushtothesun** [comment] 2017-12-28 03:30
Happened again trying to sell a Level 19 20% Added Lightning Support. No error on clipboarding. I think it has to do with length. If I pasted in explorer I saw the added lightning paste but pasting in search on POE nothing happened. So I shorted it and it pasted just fine. It seems the search box has a character limit where if you go past it, it just won't paste anything.

**Comment by EThaNol2005** [comment] 2017-12-28 10:14
I can confirm, same issus with some gems.

**Comment by lemasato** [comment] 2018-01-10 22:29
Should be fixed now.  
There is indeed a char limit (50) for the in-game stash search.

Since searching for quality gems takes quite a lot of space, I have reduced it to simply "y: +x%" (instead of "quality: +x%") and "l: x" (instead of level: x). In the case where that would still not be enough to get under the character limit, the gem name will be trimmed.

**Closed** 2018-01-30 20:40 UTC
Labels: awaiting feedback, bug
