### ISSUE TITLE
Again virus detection

### ISSUE THREAD

**Issue by EThaNol2005** [lemasato/POE-Trades-Companion#143] opened 2018-09-03 20:49 UTC
here we go again-.-

https://www.virustotal.com/de/file/72768b2ac6af1e54ff4f02b606f02e637f0922580f5dbb31bc345aea20fd9688/analysis/1536007635/

**Comment by lemasato** [comment] 2018-09-03 20:52
I know. This issue probably won't go away.  
I'm thinking on contacting antivirus companies to get it fixed, but didn't have the time yet. Also, not really sure if that would be any useful as it could come back once a new version is released.

**Comment by rushtothesun** [comment] 2018-09-03 22:18
Honestly I know it's a false positive, but what annoys me is bitdefender and MBAM going ape-shit over it. I don't know how many times i had to exclude it. One exclusion on both for the file, then having to turn both off because if it auto updates it'll flag the temp file. Then having to download it manually and add another exclusion for that file in both. Then bitdefender stopping it from running and me having to allow it to modify files. Jesus.

**Comment by lemasato** [comment] 2018-09-03 23:41
@rushtothesun Hey. Since 1.13, you can now auto-update the source as well.  
I would highly recommend using it until the issue is "fixed".  
Just download "Source-only-no-exe.zip" from the releases page.

**Comment by EThaNol2005** [comment] 2018-09-04 14:32
How i use the command line with ahk?

**Comment by lemasato** [comment] 2018-09-04 14:41
Pretty much the same.  
Just make a shortcut of the .ahk script and add your parameters.  
Example:
```
"H:\UserLibrary\Documents\GitHub\POE-Trades-Companion\POE Trades Companion.ahk" /InstanceName="Shop" /GameFolder="C:\Games\Path of Exile"
```

**Comment by lemasato** [comment] 2018-09-06 12:29
I'll be closing this.
For any talk about the virus flagging, please head to #124 
But I know... This issue annoys me just as much as every one of you :/

**Closed by lemasato** 2018-09-06 12:29 UTC
