### ISSUE TITLE
Tried installing, now POE won't launch

### ISSUE THREAD

**Issue by SRSFAN** [lemasato/POE-Trades-Companion#102] opened 2018-04-16 06:34 UTC
Really not sure what to do. I tried uninstalling everything and reinstalling POE with no extensions/macros and it still gives this error: "Font: Fontin Smallcaps': In source code file: Resource\FontResourceWindows.cpp at line 57, Processing fille: Font: Fontin Smallcaps Error: failed to get text metrics."

I noticed Fontin Smallcaps was a file in the .zip and thought there might be some relation. Not sure what to do! I tried following guides on overcoming failed text metric issues but nothing is working and my game won't even launch now.

**Comment by lemasato** [comment] 2018-04-16 07:15
Sounds like a conflict between the game's font and the one included in Trades Companion.

Have you tried rebooting yet?

**Comment by Bagindo4ka** [comment] 2018-04-30 21:51
Got this eror today

**Comment by lemasato** [comment] 2018-04-30 22:40
Some solutions you may want to try:
**** 
### Manually reinstalling the font from Trades Companion local folder
1. Close Trades Companion.
1. Head to `\Documents\AutoHotkey\POE Trades Companion\Fonts`.
1. Right click on Fontin-SmallCaps.ttf, choose Install, accept to replace.
1. Reboot, and try launching POE again.
1. If the game is now working, close it then start Trades Companion.
Now, start the game again and see if the issue is fixed.

### Uninstalling the font from Windows
1. Close Trades Companion.
1. Head to `C:\Windows\Fonts
1. Find "Fontin SmallCaps", right click, choose Remove
1. Reboot, and try launching POE again.
1. If the game is now working, close it then start Trades Companion.
Now, start the game again and see if the issue is fixed.

### Removing the font file from Windows
Download and install [LockHunter](https://lockhunter.com/downloadnow.htm).
1. Close Trades Companion.
1. Open an explorer window, and change the path to ` \\localhost\c$\Windows\Fonts`
1. Sort by title (Right click > Sort by > Title)
1. For every font titled "Fontin SmallCaps" or "Fontin-SmallCaps": Right click on the file > What is locking this file? > Wait until LockHunter shows up and choose "Delete It!"
1. Reboot, and try launching POE again.
1. If the game is now working, close it then start Trades Companion.
Now, start the game again and see if the issue is fixed.

**Closed** 2018-06-03 20:33 UTC
Labels: awaiting feedback, support
