### ISSUE TITLE
Ctrl+Shift+LMB prevented from working (vendor bulk buy)

### ISSUE THREAD

**Issue by tonpix** [lemasato/POE-Trades-Companion#185] opened 2018-12-27 12:04 UTC
FYI, 3.5 introduced this new hotkey, so you can buy faster stuff from vendor (hello fuses :), but I noticed it doesn't stop when PTC is launched (it's like only Ctrl is working, getting fuses one by one in backpack), exiting app makes hotkey working again.

When I checked settings, I couldn't find any related hotkeys that could overlap/conflict. Any ideas?

**Comment by lemasato** [comment] 2018-12-28 20:56
As explained [here](https://github.com/lemasato/POE-Trades-Companion/issues/182#issuecomment-449629021), Ctrl+Shift+Click allows to get just the right amount of currency the buyer is requesting.  
This hotkey is activated at all time, and it most likely (can't check now to confirm) is sending Ctrl+Click if no currency is found.  
If the issue is confirmed, it will be fixed in the next version, thank you for reporting.

**Comment by lemasato** [comment] 2019-02-25 13:12
This will be fixed on the next update.
If you wish, you can use it now by [downloading the master zip](https://github.com/lemasato/POE-Trades-Companion/archive/master.zip)

**Closed by lemasato** 2019-02-25 13:12 UTC
Labels: bug
