### ISSUE TITLE
Purchase Tabs

### ISSUE THREAD

**Issue by rstroop** [lemasato/POE-Trades-Companion#164] opened 2018-09-24 21:28 UTC
Could you bring up tabs when we send a whisper to someone to buy something (assuming it uses the copy format from poe.trade)? We could benefit from the same buttons: party/trade/thank you when we do a purchase just like a sale. And if that could be logged it would be nice to remember what we bought items for if we want to sell them later. Also having tabs would allow us to send multiple offers to different people and when someone finally responds we could switch to that tab and see what the cost was for their listing. Thanks!

**Comment by lemasato** [comment] 2018-09-28 09:00
Not really possible, due to how the current Trades GUI works.  
Adding a second tabs row would just make things uneasy.  

It has been asked multiple times, and I would always decline the idea [due to how buying item works](https://github.com/lemasato/POE-Trades-Companion/issues/120#issuecomment-408387340).  

But yeah. I could make a second GUI that would log trading whispers sent.  
It would have only the bare minimum such as "Seller / Item / Price" and "Whisper / Hideout / Thanks / Close". Though I'm not really sure when and if I would like to work on that.  

I'll be leaving this open as it could potentially be a nice improvement.

**Comment by faraddox** [comment] 2018-12-13 04:50
Used mercury trade before, and switched to this cause mercury didn't update along. Mercury just adds tabs in row for sellers and buyers together. Want to see it here too, cause most of currency traders just ignore us or send invite later, and without tabs it is too hard to find what trade did you send for this trader.

**Comment by Pegoth** [comment] 2019-03-19 14:36
Would really like this feature, want to switch from MercuryTrade, but without outgoin message support I cannot fully switch.

**Comment by fladson** [comment] 2019-03-19 20:42
+1 for this
the _/whois_ and re-send are so helpful when buying from people that are busy or afk

**Comment by stu177** [comment] 2019-03-28 20:39
I don't understand your reasoning for not implementing this as described in #120. If the seller switches character, yes the names wont match up but the game will still send the message to the account, regardless of what character they are on.

It seems like that is an edge case and people would accept that as a limitation. Not having outgoing trade support is the only reason I continue to use Mercury Trade of POE Trades Companion.

**Comment by zorgshanker** [comment] 2019-03-29 00:09
They don't have to switch characters in between. They just have to be on a different character than the one our original whisp has been sent to.

That said, this is pretty much what I would like tabs to solve for me.

Maybe you could use some other elements of the outgoing whisps to differentiate them and potentially some kind of confidence indicator if uniqueness of the tab can't be proven.

**Comment by stu177** [comment] 2019-03-29 00:45
I'm still unsure how this is a problem, why does it matter for the buyer, what character the seller is on?

**Comment by zorgshanker** [comment] 2019-03-29 01:02
I believe it's because PTC can't know which trade is which, at least in
some cases. e.g. you send 2 whispers for the same amount of the same item
for the same price to 2 different people. It won't be able to identify with
certainty which trade is which when you get a reply or invite back. As it's
fairly likely they're on a different toon than the one listed.

Which is why I suggest some kind of confidence indicator or warning if it
can't make a 100% match.

I do agree with you though that all of the above is fairly trivial and not
a big deal though. Most of the time sequential outgoing whispers are
unique. Between item names, quantity, and price I'm fairly sure most trades
would be unique and identifiable thus making this a worthwhile feature to
implement.

**Comment by lemasato** [comment] 2019-03-29 20:26
The issue is(was?) that *(at least it used to be like this back when I did testings)*, the character name on poe.trade was always the highest level in the current challenge league.  
If your highest char in Synthesis was 90, and you'd be playing on a new character for a while, poe.trade would still show the level 90 char name. Only when your new character would reach level 91 would poe.trade show that character's name.  

It would cause some issue as, after receiving a party invite, you'd be looking for that person's name on the interface, but you would never be able to find it as you actually whispered another character from that person's account.  

Though, it seems to have changed now.  
After a few minutes, it uses the character you are currently logged on.  
*(at least, it used to be like this when I did testings again last league)*  

Anyway, this has been asked a few times on Discord too, and it'll most likely happen.  
And to be honest, even if that "bug" still happened, it wouldn't matter as I don't think it would be that common.  
Got some idea for the interface, and how it'd work. Simply need free time to work on it.

**Comment by JusKillmeQik** [comment] 2019-06-11 16:50
It seems like you've implemented this now, and it's very useful. Is there anyway to customize the buttons for this as well? For example, after I say thank you, I'd like to leave the party and go to my hideout.

**Comment by livejamie** [comment] 2019-06-17 20:58
With all due respect, I _really_ want a way to turn this off or disable it.

Sometimes will try to buy Fossils and I end up whispering hundreds of people - it's very annoying in that instance.

Thanks so much for your hard work @lemasato

**Comment by lemasato** [comment] 2019-06-17 21:03
@JusKillmeQik No customization planned for now.

@livejamie It's silly how many times I get asked this. It's right in the tray menu :p 
![image](https://user-images.githubusercontent.com/14184969/59636533-06ddf280-9154-11e9-848d-66bc331e83a5.png)

**Comment by livejamie** [comment] 2019-06-18 01:38
I don't have that option.

I'm using 1.15.BETA_4

![image](https://user-images.githubusercontent.com/49513/59647154-fc5d3200-912e-11e9-8ee9-01a1789cff29.png)

**Comment by lemasato** [comment] 2019-06-18 01:42
@livejamie Yup, it was added on BETA_5

**Comment by livejamie** [comment] 2019-06-18 01:43
Oh I thought it would have updated for me, sorry.

**Comment by lemasato** [comment] 2019-06-18 01:52
@livejamie Aren't you getting automated updates?
Can you check if BETA are enabled in Settings>Updating?

Anyway, even if disabled, you should get a tray notification on app start if an update is available. Isn't that working?

**Comment by lemasato** [comment] 2020-02-12 01:20
I'll be closing this issue to keep the issues tab cleaner as those are either already available in the latest ALPHA or on my consider/to-do list.  
If you wish to try it out, the ALPHA is available on the Discord server. Though, it is really only recommended for testings purpose and not meant to be used to replace the latest BETA.

**Closed by lemasato** 2020-02-12 01:20 UTC
Labels: enhancement, not now
