### ISSUE TITLE
GUI Scaling Issue

### ISSUE THREAD

**Issue by argosreality** [lemasato/POE-Trades-Companion#137] opened 2018-09-02 18:57 UTC
![poe_companion-issue](https://user-images.githubusercontent.com/41969396/44959667-230fec00-aec0-11e8-8bcc-28553332ffa8.jpg)  Since the rework the GUI doesnt seem to be scaling properly as its not displaying atleast three of the action buttons. Version is 1.13.1 

I am using display scaling of 125% in Windows
OS Windows 10 1803

**Comment by lemasato** [comment] 2018-09-02 20:50
Yup. Duplicate of #132 , but thank you for reporting!

**Closed by lemasato** 2018-09-02 20:50 UTC
