### ISSUE TITLE
Random hang time between sending button actions, occasionally. [Beta_10]

### ISSUE THREAD

**Issue by Megaddd** [lemasato/POE-Trades-Companion#79] opened 2017-08-27 11:25 UTC
Occasionally after pressing Invite to Party or Thank You! (or any other 2-action buttons), the first action is sent, and the whole script freezes for several seconds, then sends the second action and everything resumes normally.

Cause as of yet unknown.

**Comment by lemasato** [comment] 2017-08-27 18:09
Strange...
Code-wise, there isn't any wait in-between messages.
And the only thing happening in the background is monitoring the chat logs, but it's timer based (no sleep occurring) and there isn't much going on in there.

**Comment by Megaddd** [comment] 2017-08-27 18:48
I got you a few stramable clips of when it happened to me several times today. 

1: https://streamable.com/5basi
2: https://streamable.com/zpppa
3: https://streamable.com/3zh9c
4: https://streamable.com/0jxxz
5: https://streamable.com/0ggcx

The common theme in most of these is that between button action #1 and button action #2 I get either a trade or a message, however that is not the case in 'clip 4'. So if that is not the cause I'm puzzled as to what may cause this.

**Comment by lemasato** [comment] 2017-08-28 16:06
I have had a script write to the file constantly. Simulated 1000 button presses. No issues.
Then I did it again, but this time including a trading whisper once in a while.  When the trading whisper would be processed, the script would indeed hang, but only for a split second before continuing its normal operations.

```
These testings lead me to the discovery of a new issue.
- Having "Clipboard item on tab switch" enabled.
- Receiving a trading whisper the very same moment we are sending the custom message.

Since the clipboard will be replaced by the tab's item, it will send that instead on the custom message.
```

**Comment by lemasato** [comment] 2017-09-01 15:14
Hi there,
I have added a potential fix for this issue in [1.12.BETA_11](https://github.com/lemasato/POE-Trades-Companion/releases/tag/1.12.BETA_11).
Could you try it out and report back?

**Comment by Megaddd** [comment] 2017-09-01 15:35
I have since determined that, since you use the clipboard as confirmation that the game is responsive, that my clipboard manager might potentially be screwing with the responsiveness from time to time. I haven't  had any issues since disabling it, yet. Will post if I do.

**Comment by Megaddd** [comment] 2017-09-03 17:17
No more hangs present. After a few days of usage.

**Comment by lemasato** [comment] 2017-09-09 19:52
Alright, thanks for confirming the cause!
I will be adding something about this in the FAQ.

**Closed by lemasato** 2017-09-09 19:52 UTC
Labels: awaiting feedback, bug, not sure
