### ISSUE TITLE
Trades not detected

### ISSUE THREAD

**Issue by tootin** [lemasato/POE-Trades-Companion#71] opened 2017-08-15 20:07 UTC
The app stopped working for me around a day and half ago. The macro functions still work but it does not seem to be able to track that I have a trade coming in. 

I have ran as administrator. I have also deleted the application and reinstalled. 

Any help getting this fixed would be much appreciated. I love this app and it makes trading so hassle free.

**Comment by lemasato** [comment] 2017-08-15 20:23
Which version are you using? Stable or BETA?
It most likely won't help but could you zip and upload the logs folder (Documents\AutoHotkey\POE Trades Companion\Logs)

**Comment by tootin** [comment] 2017-08-15 20:38
[Logs.zip](https://github.com/lemasato/POE-Trades-Companion/files/1226351/Logs.zip)
I have tried using both versions no such luck. I was having some problems with PoE client recently, and had to switch to steam. Recently switched back to their stand alone after reinstalling. Could this have caused an issue?

**Comment by lemasato** [comment] 2017-08-15 20:58
Nope, it works both with steam and standalone. Switching back and forth will not cause issues.
In one of the logs, it did not detect the game's Client.txt file (Probably because you didn't run PoE at the time), but on the second it's pointing at `C:\Program Files (x86)\Grinding Gear Games\Path of Exile\logs\Client.txt`, is this location correct?

Also, please follow these few steps: 
- Download the [latest beta source](https://github.com/lemasato/POE-Trades-Companion/archive/1.12.BETA_8.zip) and extract it.
- Download and install [AutoHotKey](https://autohotkey.com/download/) if you didn't have it already.
- Run `POE Trades Companion.ahk`
- Head in game, inside your hideout send this message in the local chat: 
`aze @From iSellStuff: Hi, I would like to buy your ITEM listed for PRICE in Harbinger`

Does the Trades GUI update to display the whisper infos?

**Comment by tootin** [comment] 2017-08-15 21:04
Yes that is the correct path. I did all the steps above and it did not display it.

**Comment by lemasato** [comment] 2017-08-15 21:12
Can you head back to the logs folder, open the most recent file (look at the last modified time), scroll until the very bottom and see if it says `[2017/08/15 22:58:57] Monitoring game logs file: D:\Path of Exile\logs\Client.txt` ?

One last thing you could do is:
- Open the Debug.json file
- Change `"use_chat_logs" : false,` to `true`
- Then run POE Trades Companion.ahk

As soon as the tool is launched, some trades should appear.
If it works, it could be something that prevent us from reading the Client.txt file.  
If it does not, there's most likely an issue with your system, though I can't say what exactly.

**Comment by tootin** [comment] 2017-08-15 21:18
Looks like they were all lasted updated the same day 8/13/2017 I believe thats the day I reinstalled it. Might not have had the app working since then. Last line is 2017/08/13 01:52:07 89029750 257 [INFO Client 5068] Finished checking files

**Comment by tootin** [comment] 2017-08-15 21:26
Nothing appeared when I changed the debug file it loaded like normal no popups.

**Comment by tootin** [comment] 2017-08-15 21:30
I am reinstalling the steam version on the same drive now to test if its possibly something with the drive.

**Comment by tootin** [comment] 2017-08-15 21:38
Okay so reinstalled the steam version and it works there.

**Comment by lemasato** [comment] 2017-08-15 21:39
Oops, you are actually looking at the game logs. I meant the program logs.
`\Documents\AutoHotkey\POE Trades Companion\Logs`

Though, if you played recently and the game logs shows 13th of August, that's definitely an issue.
It could be that the Client.txt file is set to read only.
Right click on the Client.txt file > Properties. Make sure "Ready only" is unchecked.

> Nothing appeared when I changed the debug file it loaded like normal no popups.

Now that's a weird one.
Right click on the POE Trades Companion.ahk file > Properties.
Click on the "Unblock" button if there is. [For reference](https://www.microsystools.com/help/all/unlock-software-unblock.png)

> Okay so reinstalled the steam version and it works there.

Good to know! Double check if the standalone Client.txt is not set as read-only.

**Comment by tootin** [comment] 2017-08-15 21:44
They are not but the Path of Exile folder itself is and all subfolders. 
![dllhost_2017-08-15_17-43-21](https://user-images.githubusercontent.com/23311449/29337957-62a82dda-81e1-11e7-963a-d94d36afe8aa.png)

**Comment by lemasato** [comment] 2017-08-15 22:14
This is expected, do not change it. That's the way the game set it up.
It actually means "some files are set as read-only, but not the entire folder".

Now that we know it works for the Steam client, let's go step by step:
(I recommend using the latest beta version: 1.12.BETA_8)
- Close any PoE instances.
- Run POE Trades Companion, without loading the game.
- Does it say "No game instance could be found, retrying in ..."?
- - If yes, all good, continue.
- - If not, report back here.
- Head to your standalone game folder, and run the game.
- After a few seconds, the GUI should now show "No trade on queue ..."
- At this point, head to the program's logs folder (Documents\AutoHotkey\POE Trades Companion\Logs) and look for the most recent logs file. Open it, check if the latest line says "Monitoring game logs file".
- - If yes, continue.
- - If not, that means there is an issue with detecting the logs file.
- Now that it's monitoring the logs, send in the local chat the message I specified earlier.
- At this point, the GUI should now update and show the whisper informations.

**Comment by tootin** [comment] 2017-08-15 22:24
Without the game open only the ahk I get All trade request have been answered. 
https://puu.sh/xb0zP/bfeecb702e.png

**Comment by tootin** [comment] 2017-08-15 22:31
All went well until I sent the msg and then nothing. The advanced macros still work but trades do not. Closed game and ahk. Relaunched steam version, and then relaunched the apk, and it worked fine once again.

**Comment by lemasato** [comment] 2017-08-15 22:42
Check the Client.txt file again, see if it gets updated when you are running the game.

**Comment by tootin** [comment] 2017-08-15 22:57
Wow thats odd no it doesnt. The steam version does but not the stand alone.

**Comment by lemasato** [comment] 2017-08-16 01:12
That's the root of the issue.
If the Client.txt files does not update, we can't read the incoming whispers.

While playing on the standalone, try seeing if steam's Client.txt gets updated.

**Comment by lemasato** [comment] 2017-08-29 22:41
I tried to reproduce the issue, but no luck.

I would recommend deleting the `Path of Exile\logs` folder, maybe that could help.
- Run the game, then exit once on the login screen.
- Open `Path of Exile\logs\Client.txt` using [Notepad++](https://notepad-plus-plus.org/download/). Make the file empty, save.
- Start the game again. At the login screen, go back to Notepad++.
- Click on "File" and choose "Reload from Disk". See if the file contains anything.

**Comment by lemasato** [comment] 2017-10-28 16:11
Hi, should this be considered fixed?

**Comment by moogle2** [comment] 2017-12-10 18:26
Happened to me today. Trades Companion starts normally with PoE turned off. There's no read-only on client.txt, but PoE is on C drive which is normally under admin rights. MercuryTrade doesn't recognize whispers either, I tried it out today. I've tried reinstalling everything except PoE and went through all the steps you gave above.

**Comment by lemasato** [comment] 2017-12-11 04:16
Yeah, this is an issue related to PoE.  

I can't seem to find any documentation related to this issue. It would be best to contact GGG directly. Either the game is unable to write to the Client.txt, or the file is located elsewhere.

For the first option:
1. Make sure that any tool interacting with the logs file is closed.
1. Close your game and delete/rename/move your Client.txt file.
1. Restart the game again then close it at the login screen.
1. Did a new Client.txt appear?

If it's the second option (which is very unlikely), you could run a search on your computer for a file named "Client.txt".

&nbsp;  
> Edit; after removing client.txt, restarting, poe, shutting it down again and running companion, it says it can't detect game (with PoE off), and it throws out a logs error like logs file doesn't exist (with PoE on)

This is because the tool adds /logs/Client.txt to the location of the executable to retrieve the logs file. If you deleted the file (and the game was unable to re-create it), this will happens.

**Comment by moogle2** [comment] 2017-12-11 10:25
Tried the first option, a new Client.txt did not appear. Game doesn't generate a new one in PoE/logs folder. 

I went to PoE folder, manually set Properties - Security - Full control to Users on my PC and it works now.

**Comment by lemasato** [comment] 2017-12-28 03:03
Well, guess I'll be closing this now.  
Not an issue related to the tool, but the game/OS behaving oddly.

**Closed by lemasato** 2017-12-28 03:03 UTC
Labels: support

**Comment by TeamCatalyst** [comment] 2020-01-17 12:02
> Close any PoE instances.
Run POE Trades Companion, without loading the game.
Does it say "No game instance could be found, retrying in ..."?
If yes, all good, continue.
If not, report back here. <

Does it still say "No game instance could be found.."?
Because when I open the program before opening PoE no message like that occurs.

My reason of investigation is that my trade companion occasionally stops working.
More precisely sometimes it recognises a whisper sometimes not, resulting me not noticing the trade request via my pushbullet when I'm afk.
This happens in one session without restarting/reloading.

Also I'm using Win10, have set all security flags, files are read-able and PoE is running through Steam.

**Comment by lemasato** [comment] 2020-01-17 12:06
Most likely you're running into a Korean player. Those whispers aren't logged by GGG
https://github.com/lemasato/POE-Trades-Companion/wiki/FAQ#nothing-happens-when-i-receive-a-trading-whisper-or-some-whispers-are-ignored-notably-korean-names
