### ISSUE TITLE
Add support for https://poemap.live/

### ISSUE THREAD

**Issue by JusKillmeQik** [lemasato/POE-Trades-Companion#222] opened 2019-06-11 16:53 UTC
Trading maps is becoming more common but the standard request isn't picked up by Companion. It should be simple to parse it as a sale and show the map to grab.

example below:

I'd like to exchange my T4: (Fields) for your T4: (Excavation) in Legion

**Comment by zakaoai** [comment] 2019-06-18 17:24
I upvote

**Comment by lemasato** [comment] 2019-06-18 22:55
Yup dupe of #202 so I'll have to close this.
But this and poeapp mass buying definitely need to be added, though it's not as simple as it may seem. I could just make it so it would pop a tab for every item, but it's really not the optimal and most intuitive way to do it.

**Closed by lemasato** 2019-06-18 22:55 UTC
