### ISSUE TITLE
Whispers not being logged in Client.txt

### ISSUE THREAD

**Issue by username1001101** [lemasato/POE-Trades-Companion#236] opened 2019-06-29 17:53 UTC
Lately, I got a lot of messages, mostly from asian players (korean, japanese, chinese?) where the trade message is

"Hi, I would like to buy ...." instead of the poe.trade normal one "Hi, I'd like to buy ..."

It seems, that the "Hi, I would like to buy..." one is being parsed properly as it does not get added to the Trades Companion.

I use 1.15.BETA_9

**Comment by Kebabello** [comment] 2019-06-29 18:28
Same... pretty annoying if u got lots of spam.

**Comment by lemasato** [comment] 2019-06-29 19:16
Hey,
Actually "Hi, I'd like to..." is from currency.poe.trade.
"Hi, I would like to" is for poe.trade and ggg website.

But, this issue is related to a bug from the game, where some whispers aren't appearing in the Client.txt file, which we need:
https://www.reddit.com/r/pathofexile/comments/c6yijd/bug_important_korean_whispers_not_being_logged_in/

Sadly nothing I can do about

**Comment by Trid3nt1** [comment] 2019-06-30 11:15
It'll get fixed sooner or later then - Thank you for the response! It's awesome to know you're still actively here, keeping an eye on your addon.

**Comment by gaya2081** [comment] 2019-07-09 16:43
FYI: Per GGG not logging Korean messages is required by Korean law and is not a bug. See https://www.reddit.com/r/pathofexile/comments/c6yijd/bug_important_korean_whispers_not_being_logged_in/  and https://www.reddit.com/r/pathofexile/comments/c93tvs/bug_important_korean_whispers_not_being_logged_in/

**Comment by username1001101** [comment] 2019-07-10 07:20
So, according to GGG, there is no Facebook, WhatApp etc. in Korea as well?

**Comment by coffeecrank** [comment] 2019-07-22 09:15
I'm working on a similar tool and also saw that message from GGG mods regarding Korean laws...

What I don't understand is how come the messages TO Korean players are still getting logged then? Isn't that the same thing?

On a another note, does anyone know if maybe there's a way to scrape chat messages without going into log files? Probably not, but what if...

**Comment by lemasato** [comment] 2019-07-22 09:58
There was a small discussion around that on [Reddit](https://www.reddit.com/r/pathofexile/comments/c93tvs/bug_important_korean_whispers_not_being_logged_in/esth6tg/).

No other way to retrieve the chat messages.
Reading the process memory would obviously lead to a ban.
And OCR isn't really reliable in this case.

**Comment by coffeecrank** [comment] 2019-07-22 10:32
Man, that sucks so much. I guess half the trading will now be done without any tools/not done at all... Unless they do come up with an alternative way to log, but I also don't see that happening.

**Comment by br3edage** [comment] 2019-07-25 08:43
can you make a clause if it doesnt recognize the name (korean name) ) it would still notify you and tell you the location of the item ?

**Comment by lemasato** [comment] 2019-07-25 08:50
Can't. It's not about not recognizing the name, it's about not knowing that you received a whisper.

The tool is using a file named Client.txt, where all sorts of game informations are logged. Whispers you receive and send are logged in that file.
The thing is that any whisper received from someone playing on a Kakao account will NOT appear in this file. So basically, from our perspective, we have no idea that you received a whisper from them, and so can't do anything about it.

**Comment by lemasato** [comment] 2020-02-12 01:14
I'll be closing this issue to keep the issues tab cleaner.

**Closed by lemasato** 2020-02-12 01:14 UTC
